--
-- Script was generated by Devart dbForge Studio for MySQL, Version 8.0.40.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 9/15/2018 9:41:10 PM
-- Server version: 5.5.5-10.1.34-MariaDB
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE edificio;

--
-- Drop table `detalle`
--
DROP TABLE IF EXISTS detalle;

--
-- Drop table `pago`
--
DROP TABLE IF EXISTS pago;

--
-- Drop table `alquiler`
--
DROP TABLE IF EXISTS alquiler;

--
-- Drop table `inquilino`
--
DROP TABLE IF EXISTS inquilino;

--
-- Drop table `expensa`
--
DROP TABLE IF EXISTS expensa;

--
-- Drop table `oficina`
--
DROP TABLE IF EXISTS oficina;

--
-- Drop table `titular`
--
DROP TABLE IF EXISTS titular;

--
-- Set default database
--
USE edificio;

--
-- Create table `titular`
--
CREATE TABLE titular (
  nroTitular int(11) NOT NULL AUTO_INCREMENT,
  CI int(11) NOT NULL,
  nombre varchar(255) NOT NULL,
  teléfono int(11) NOT NULL,
  dirección varchar(50) NOT NULL,
  NIT varchar(50) NOT NULL,
  PRIMARY KEY (nroTitular)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2,
AVG_ROW_LENGTH = 16384,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create table `oficina`
--
CREATE TABLE oficina (
  nroOficina int(11) NOT NULL AUTO_INCREMENT,
  nroTitular int(11) NOT NULL,
  nombre varchar(50) NOT NULL,
  dimensión double NOT NULL,
  nroPlanta int(11) NOT NULL,
  estado varchar(255) NOT NULL,
  PRIMARY KEY (nroOficina)
)
ENGINE = INNODB,
AUTO_INCREMENT = 24,
AVG_ROW_LENGTH = 744,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create foreign key
--
ALTER TABLE oficina
ADD CONSTRAINT FK_oficina_titular_nroTitular FOREIGN KEY (nroTitular)
REFERENCES titular (nroTitular) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `expensa`
--
CREATE TABLE expensa (
  nroOficina int(11) NOT NULL AUTO_INCREMENT,
  costoTeléfono double NOT NULL,
  costoLuz double NOT NULL,
  costoAgua double NOT NULL,
  PRIMARY KEY (nroOficina)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
AVG_ROW_LENGTH = 8192,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create foreign key
--
ALTER TABLE expensa
ADD CONSTRAINT FK_expensa_oficina_nroOficina FOREIGN KEY (nroOficina)
REFERENCES oficina (nroOficina) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `inquilino`
--
CREATE TABLE inquilino (
  nroInquilino int(11) NOT NULL AUTO_INCREMENT,
  CI int(11) NOT NULL,
  nombre varchar(30) NOT NULL,
  teléfono int(11) NOT NULL,
  dirección varchar(50) NOT NULL,
  NIT varchar(50) NOT NULL,
  PRIMARY KEY (nroInquilino)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2,
AVG_ROW_LENGTH = 16384,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create table `alquiler`
--
CREATE TABLE alquiler (
  nroAlquiler int(11) NOT NULL AUTO_INCREMENT,
  nroInquilino int(11) NOT NULL,
  fecha varchar(100) NOT NULL,
  PRIMARY KEY (nroAlquiler)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2,
AVG_ROW_LENGTH = 16384,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create foreign key
--
ALTER TABLE alquiler
ADD CONSTRAINT FK_alquiler_inquilino_nroInquilino FOREIGN KEY (nroInquilino)
REFERENCES inquilino (nroInquilino) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `pago`
--
CREATE TABLE pago (
  nroPago int(11) NOT NULL AUTO_INCREMENT,
  nroAlquiler int(11) NOT NULL,
  fechaPago varchar(255) NOT NULL,
  monto double NOT NULL,
  PRIMARY KEY (nroPago)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2,
AVG_ROW_LENGTH = 16384,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create foreign key
--
ALTER TABLE pago
ADD CONSTRAINT FK_pagos_alquiler_nroAlquiler FOREIGN KEY (nroAlquiler)
REFERENCES alquiler (nroAlquiler) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `detalle`
--
CREATE TABLE detalle (
  nroDetalle int(11) NOT NULL AUTO_INCREMENT,
  nroAlquiler int(11) NOT NULL,
  nroOficina int(11) NOT NULL,
  precioOficina int(11) NOT NULL,
  PRIMARY KEY (nroDetalle)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2,
AVG_ROW_LENGTH = 16384,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create foreign key
--
ALTER TABLE detalle
ADD CONSTRAINT FK_detalle1_alquiler_nroAlquiler FOREIGN KEY (nroAlquiler)
REFERENCES alquiler (nroAlquiler) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE detalle
ADD CONSTRAINT FK_detalle1_oficina_nroOficina FOREIGN KEY (nroOficina)
REFERENCES oficina (nroOficina) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- 
-- Dumping data for table titular
--
INSERT INTO titular VALUES
(1, 3000531, 'Blanca Cadima', 73794042, 'Jordan E#147', '3000531013');

-- 
-- Dumping data for table inquilino
--
INSERT INTO inquilino VALUES
(1, 5919874, 'Agencia', 4501212, 'calle nose', '5464978');

-- 
-- Dumping data for table oficina
--
INSERT INTO oficina VALUES
(1, 1, 'Of. 1', 100, 0, 'Ocupado'),
(2, 1, 'Of. 2', 100, 0, 'Ocupado'),
(3, 1, 'Of. 3', 50, 0, 'Ocupado'),
(4, 1, 'Of. 4', 25, 0, 'Ocupado'),
(5, 1, 'Of. 5', 100, 0, 'Ocupado'),
(6, 1, 'Of. 6', 50, 0, 'Ocupado'),
(7, 1, 'Of. 7', 100, 0, 'Ocupado'),
(8, 1, 'Of. 101', 50, 1, 'Ocupado'),
(9, 1, 'Of. 102', 50, 1, 'Ocupado'),
(10, 1, 'Of. 103', 50, 1, 'Ocupado'),
(11, 1, 'Of. 104', 50, 1, 'Ocupado'),
(12, 1, 'Of. 105', 50, 1, 'Ocupado'),
(13, 1, 'Of. 106', 50, 1, 'Ocupado'),
(14, 1, 'Of. 107', 50, 1, 'Disponible'),
(15, 1, 'Of. 108', 50, 1, 'Ocupado'),
(16, 1, 'Of. 201', 50, 2, 'Disponible'),
(17, 1, 'Of. 202', 50, 2, 'Disponible'),
(18, 1, 'Of. 203', 50, 2, 'Disponible'),
(19, 1, 'Of. 204', 50, 2, 'Disponible'),
(20, 1, 'Of. 205', 50, 2, 'Disponible'),
(21, 1, 'Of. 206', 50, 2, 'Disponible'),
(22, 1, 'Of. 207', 50, 2, 'Disponible'),
(23, 1, 'Of. 208', 50, 2, 'Disponible');

-- 
-- Dumping data for table alquiler
--
INSERT INTO alquiler VALUES
(1, 1, '15/09/2018');

-- 
-- Dumping data for table pago
--
INSERT INTO pago VALUES
(1, 1, '15/09/2018', 3500);

-- 
-- Dumping data for table expensa
--
INSERT INTO expensa VALUES
(1, 50, 10, 50),
(2, 0, 50, 50);

-- 
-- Dumping data for table detalle
--
INSERT INTO detalle VALUES
(1, 1, 1, 3500);

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;